# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  uses a generic python 3 image
parameters:
  image:
    type: string
    default: circleci/python:3.5
docker:
  - image: << parameters.image >>
